//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeachHoursEntities2 : DbContext
    {
        public TeachHoursEntities2()
            : base("name=TeachHoursEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        static TeachHoursEntities2 context;
        public static TeachHoursEntities2 GetContext()
        {
            if(context == null)
            {
                context = new TeachHoursEntities2();
            }
            return context;
        }
        public virtual DbSet<AllHours> AllHours { get; set; }
        public virtual DbSet<Dates> Dates { get; set; }
        public virtual DbSet<Hours> Hours { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teachers> Teachers { get; set; }
    }
}
